# yml(yaml)
# key: value 형식으로 작성된 파일, 구문 규칙에 따라 작성해야 한다

## server
server:
  port: 80
  servlet:
    session:
      tracking-modes: cookie

## spring
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/gooddb
    username: root
    password: 123

## mybatis
mybatis:
  mapper-locations: classpath:mapper/**/**.xml
  type-aliases-package: com.example.demo.dto.**